trigger:
  commit-match: 'dev.svctk.{{cookiecutter.application_id}}.{{cookiecutter.service_id}}.refs/heads/master'
  event-type: repo-push
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/{{cookiecutter.application_id}}/{{cookiecutter.service_id}}', '-f', '_platform/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/{{cookiecutter.application_id}}/{{cookiecutter.service_id}}']